/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorRouteImport } from './routes/_vendor'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as authUnauthorizedRouteImport } from './routes/(auth)/unauthorized'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as VendorVendorIndexRouteImport } from './routes/_vendor/vendor/index'
import { Route as VendorSubscriptionIndexRouteImport } from './routes/_vendor/subscription/index'
import { Route as AuthenticatedVendorsIndexRouteImport } from './routes/_authenticated/vendors/index'
import { Route as AuthenticatedSubcategoriesIndexRouteImport } from './routes/_authenticated/subcategories/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders/index'
import { Route as AuthenticatedDriversIndexRouteImport } from './routes/_authenticated/drivers/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedCategoriesIndexRouteImport } from './routes/_authenticated/categories/index'
import { Route as AuthenticatedAnalyticsIndexRouteImport } from './routes/_authenticated/analytics/index'
import { Route as VendorVendorSettingsRouteImport } from './routes/_vendor/vendor/settings'
import { Route as VendorVendorProfileRouteImport } from './routes/_vendor/vendor/profile'
import { Route as VendorVendorOrdersRouteImport } from './routes/_vendor/vendor/orders'
import { Route as VendorVendorMenuRouteImport } from './routes/_vendor/vendor/menu'
import { Route as VendorVendorDashboardRouteImport } from './routes/_vendor/vendor/dashboard'
import { Route as AuthenticatedAdminDeliverySettingsRouteImport } from './routes/_authenticated/admin/delivery-settings'
import { Route as AuthenticatedAdminVendorApplicationsIndexRouteImport } from './routes/_authenticated/admin/vendor-applications/index'
import { Route as AuthenticatedAdminTerangoStoreIndexRouteImport } from './routes/_authenticated/admin/terango-store/index'
import { Route as AuthenticatedAdminTerangoProductsIndexRouteImport } from './routes/_authenticated/admin/terango-products/index'
import { Route as AuthenticatedAdminSubscriptionsIndexRouteImport } from './routes/_authenticated/admin/subscriptions/index'
import { Route as AuthenticatedAdminFeaturedIndexRouteImport } from './routes/_authenticated/admin/featured/index'
import { Route as AuthenticatedAdminBroadcastsIndexRouteImport } from './routes/_authenticated/admin/broadcasts/index'
import { Route as AuthenticatedAdminAnalyticsIndexRouteImport } from './routes/_authenticated/admin/analytics/index'
import { Route as AuthenticatedAdminAdvertisementsIndexRouteImport } from './routes/_authenticated/admin/advertisements/index'
import { Route as AuthenticatedAdminTerangoStoreSettingsRouteImport } from './routes/_authenticated/admin/terango-store/settings'
import { Route as AuthenticatedAdminTerangoStoreOrdersRouteImport } from './routes/_authenticated/admin/terango-store/orders'

const VendorRoute = VendorRouteImport.update({
  id: '/_vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authUnauthorizedRoute = authUnauthorizedRouteImport.update({
  id: '/(auth)/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorVendorIndexRoute = VendorVendorIndexRouteImport.update({
  id: '/vendor/',
  path: '/vendor/',
  getParentRoute: () => VendorRoute,
} as any)
const VendorSubscriptionIndexRoute = VendorSubscriptionIndexRouteImport.update({
  id: '/subscription/',
  path: '/subscription/',
  getParentRoute: () => VendorRoute,
} as any)
const AuthenticatedVendorsIndexRoute =
  AuthenticatedVendorsIndexRouteImport.update({
    id: '/vendors/',
    path: '/vendors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubcategoriesIndexRoute =
  AuthenticatedSubcategoriesIndexRouteImport.update({
    id: '/subcategories/',
    path: '/subcategories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDriversIndexRoute =
  AuthenticatedDriversIndexRouteImport.update({
    id: '/drivers/',
    path: '/drivers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCategoriesIndexRoute =
  AuthenticatedCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const VendorVendorSettingsRoute = VendorVendorSettingsRouteImport.update({
  id: '/vendor/settings',
  path: '/vendor/settings',
  getParentRoute: () => VendorRoute,
} as any)
const VendorVendorProfileRoute = VendorVendorProfileRouteImport.update({
  id: '/vendor/profile',
  path: '/vendor/profile',
  getParentRoute: () => VendorRoute,
} as any)
const VendorVendorOrdersRoute = VendorVendorOrdersRouteImport.update({
  id: '/vendor/orders',
  path: '/vendor/orders',
  getParentRoute: () => VendorRoute,
} as any)
const VendorVendorMenuRoute = VendorVendorMenuRouteImport.update({
  id: '/vendor/menu',
  path: '/vendor/menu',
  getParentRoute: () => VendorRoute,
} as any)
const VendorVendorDashboardRoute = VendorVendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => VendorRoute,
} as any)
const AuthenticatedAdminDeliverySettingsRoute =
  AuthenticatedAdminDeliverySettingsRouteImport.update({
    id: '/admin/delivery-settings',
    path: '/admin/delivery-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminVendorApplicationsIndexRoute =
  AuthenticatedAdminVendorApplicationsIndexRouteImport.update({
    id: '/admin/vendor-applications/',
    path: '/admin/vendor-applications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTerangoStoreIndexRoute =
  AuthenticatedAdminTerangoStoreIndexRouteImport.update({
    id: '/admin/terango-store/',
    path: '/admin/terango-store/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTerangoProductsIndexRoute =
  AuthenticatedAdminTerangoProductsIndexRouteImport.update({
    id: '/admin/terango-products/',
    path: '/admin/terango-products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSubscriptionsIndexRoute =
  AuthenticatedAdminSubscriptionsIndexRouteImport.update({
    id: '/admin/subscriptions/',
    path: '/admin/subscriptions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFeaturedIndexRoute =
  AuthenticatedAdminFeaturedIndexRouteImport.update({
    id: '/admin/featured/',
    path: '/admin/featured/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBroadcastsIndexRoute =
  AuthenticatedAdminBroadcastsIndexRouteImport.update({
    id: '/admin/broadcasts/',
    path: '/admin/broadcasts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsIndexRoute =
  AuthenticatedAdminAnalyticsIndexRouteImport.update({
    id: '/admin/analytics/',
    path: '/admin/analytics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAdvertisementsIndexRoute =
  AuthenticatedAdminAdvertisementsIndexRouteImport.update({
    id: '/admin/advertisements/',
    path: '/admin/advertisements/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTerangoStoreSettingsRoute =
  AuthenticatedAdminTerangoStoreSettingsRouteImport.update({
    id: '/admin/terango-store/settings',
    path: '/admin/terango-store/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTerangoStoreOrdersRoute =
  AuthenticatedAdminTerangoStoreOrdersRouteImport.update({
    id: '/admin/terango-store/orders',
    path: '/admin/terango-store/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/unauthorized': typeof authUnauthorizedRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/delivery-settings': typeof AuthenticatedAdminDeliverySettingsRoute
  '/vendor/dashboard': typeof VendorVendorDashboardRoute
  '/vendor/menu': typeof VendorVendorMenuRoute
  '/vendor/orders': typeof VendorVendorOrdersRoute
  '/vendor/profile': typeof VendorVendorProfileRoute
  '/vendor/settings': typeof VendorVendorSettingsRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/categories': typeof AuthenticatedCategoriesIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/drivers': typeof AuthenticatedDriversIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/subcategories': typeof AuthenticatedSubcategoriesIndexRoute
  '/vendors': typeof AuthenticatedVendorsIndexRoute
  '/subscription': typeof VendorSubscriptionIndexRoute
  '/vendor': typeof VendorVendorIndexRoute
  '/admin/terango-store/orders': typeof AuthenticatedAdminTerangoStoreOrdersRoute
  '/admin/terango-store/settings': typeof AuthenticatedAdminTerangoStoreSettingsRoute
  '/admin/advertisements': typeof AuthenticatedAdminAdvertisementsIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsIndexRoute
  '/admin/broadcasts': typeof AuthenticatedAdminBroadcastsIndexRoute
  '/admin/featured': typeof AuthenticatedAdminFeaturedIndexRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsIndexRoute
  '/admin/terango-products': typeof AuthenticatedAdminTerangoProductsIndexRoute
  '/admin/terango-store': typeof AuthenticatedAdminTerangoStoreIndexRoute
  '/admin/vendor-applications': typeof AuthenticatedAdminVendorApplicationsIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/unauthorized': typeof authUnauthorizedRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/delivery-settings': typeof AuthenticatedAdminDeliverySettingsRoute
  '/vendor/dashboard': typeof VendorVendorDashboardRoute
  '/vendor/menu': typeof VendorVendorMenuRoute
  '/vendor/orders': typeof VendorVendorOrdersRoute
  '/vendor/profile': typeof VendorVendorProfileRoute
  '/vendor/settings': typeof VendorVendorSettingsRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/categories': typeof AuthenticatedCategoriesIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/drivers': typeof AuthenticatedDriversIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/subcategories': typeof AuthenticatedSubcategoriesIndexRoute
  '/vendors': typeof AuthenticatedVendorsIndexRoute
  '/subscription': typeof VendorSubscriptionIndexRoute
  '/vendor': typeof VendorVendorIndexRoute
  '/admin/terango-store/orders': typeof AuthenticatedAdminTerangoStoreOrdersRoute
  '/admin/terango-store/settings': typeof AuthenticatedAdminTerangoStoreSettingsRoute
  '/admin/advertisements': typeof AuthenticatedAdminAdvertisementsIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsIndexRoute
  '/admin/broadcasts': typeof AuthenticatedAdminBroadcastsIndexRoute
  '/admin/featured': typeof AuthenticatedAdminFeaturedIndexRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsIndexRoute
  '/admin/terango-products': typeof AuthenticatedAdminTerangoProductsIndexRoute
  '/admin/terango-store': typeof AuthenticatedAdminTerangoStoreIndexRoute
  '/admin/vendor-applications': typeof AuthenticatedAdminVendorApplicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_vendor': typeof VendorRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/unauthorized': typeof authUnauthorizedRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/delivery-settings': typeof AuthenticatedAdminDeliverySettingsRoute
  '/_vendor/vendor/dashboard': typeof VendorVendorDashboardRoute
  '/_vendor/vendor/menu': typeof VendorVendorMenuRoute
  '/_vendor/vendor/orders': typeof VendorVendorOrdersRoute
  '/_vendor/vendor/profile': typeof VendorVendorProfileRoute
  '/_vendor/vendor/settings': typeof VendorVendorSettingsRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/_authenticated/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/drivers/': typeof AuthenticatedDriversIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/subcategories/': typeof AuthenticatedSubcategoriesIndexRoute
  '/_authenticated/vendors/': typeof AuthenticatedVendorsIndexRoute
  '/_vendor/subscription/': typeof VendorSubscriptionIndexRoute
  '/_vendor/vendor/': typeof VendorVendorIndexRoute
  '/_authenticated/admin/terango-store/orders': typeof AuthenticatedAdminTerangoStoreOrdersRoute
  '/_authenticated/admin/terango-store/settings': typeof AuthenticatedAdminTerangoStoreSettingsRoute
  '/_authenticated/admin/advertisements/': typeof AuthenticatedAdminAdvertisementsIndexRoute
  '/_authenticated/admin/analytics/': typeof AuthenticatedAdminAnalyticsIndexRoute
  '/_authenticated/admin/broadcasts/': typeof AuthenticatedAdminBroadcastsIndexRoute
  '/_authenticated/admin/featured/': typeof AuthenticatedAdminFeaturedIndexRoute
  '/_authenticated/admin/subscriptions/': typeof AuthenticatedAdminSubscriptionsIndexRoute
  '/_authenticated/admin/terango-products/': typeof AuthenticatedAdminTerangoProductsIndexRoute
  '/_authenticated/admin/terango-store/': typeof AuthenticatedAdminTerangoStoreIndexRoute
  '/_authenticated/admin/vendor-applications/': typeof AuthenticatedAdminVendorApplicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/unauthorized'
    | '/'
    | '/admin/delivery-settings'
    | '/vendor/dashboard'
    | '/vendor/menu'
    | '/vendor/orders'
    | '/vendor/profile'
    | '/vendor/settings'
    | '/analytics'
    | '/categories'
    | '/customers'
    | '/drivers'
    | '/orders'
    | '/reports'
    | '/subcategories'
    | '/vendors'
    | '/subscription'
    | '/vendor'
    | '/admin/terango-store/orders'
    | '/admin/terango-store/settings'
    | '/admin/advertisements'
    | '/admin/analytics'
    | '/admin/broadcasts'
    | '/admin/featured'
    | '/admin/subscriptions'
    | '/admin/terango-products'
    | '/admin/terango-store'
    | '/admin/vendor-applications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/unauthorized'
    | '/'
    | '/admin/delivery-settings'
    | '/vendor/dashboard'
    | '/vendor/menu'
    | '/vendor/orders'
    | '/vendor/profile'
    | '/vendor/settings'
    | '/analytics'
    | '/categories'
    | '/customers'
    | '/drivers'
    | '/orders'
    | '/reports'
    | '/subcategories'
    | '/vendors'
    | '/subscription'
    | '/vendor'
    | '/admin/terango-store/orders'
    | '/admin/terango-store/settings'
    | '/admin/advertisements'
    | '/admin/analytics'
    | '/admin/broadcasts'
    | '/admin/featured'
    | '/admin/subscriptions'
    | '/admin/terango-products'
    | '/admin/terango-store'
    | '/admin/vendor-applications'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_vendor'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(auth)/unauthorized'
    | '/_authenticated/'
    | '/_authenticated/admin/delivery-settings'
    | '/_vendor/vendor/dashboard'
    | '/_vendor/vendor/menu'
    | '/_vendor/vendor/orders'
    | '/_vendor/vendor/profile'
    | '/_vendor/vendor/settings'
    | '/_authenticated/analytics/'
    | '/_authenticated/categories/'
    | '/_authenticated/customers/'
    | '/_authenticated/drivers/'
    | '/_authenticated/orders/'
    | '/_authenticated/reports/'
    | '/_authenticated/subcategories/'
    | '/_authenticated/vendors/'
    | '/_vendor/subscription/'
    | '/_vendor/vendor/'
    | '/_authenticated/admin/terango-store/orders'
    | '/_authenticated/admin/terango-store/settings'
    | '/_authenticated/admin/advertisements/'
    | '/_authenticated/admin/analytics/'
    | '/_authenticated/admin/broadcasts/'
    | '/_authenticated/admin/featured/'
    | '/_authenticated/admin/subscriptions/'
    | '/_authenticated/admin/terango-products/'
    | '/_authenticated/admin/terango-store/'
    | '/_authenticated/admin/vendor-applications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  VendorRoute: typeof VendorRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  authUnauthorizedRoute: typeof authUnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_vendor': {
      id: '/_vendor'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/unauthorized': {
      id: '/(auth)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof authUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_vendor/vendor/': {
      id: '/_vendor/vendor/'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorVendorIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/_vendor/subscription/': {
      id: '/_vendor/subscription/'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof VendorSubscriptionIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/_authenticated/vendors/': {
      id: '/_authenticated/vendors/'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedVendorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subcategories/': {
      id: '/_authenticated/subcategories/'
      path: '/subcategories'
      fullPath: '/subcategories'
      preLoaderRoute: typeof AuthenticatedSubcategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drivers/': {
      id: '/_authenticated/drivers/'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AuthenticatedDriversIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories/': {
      id: '/_authenticated/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_vendor/vendor/settings': {
      id: '/_vendor/vendor/settings'
      path: '/vendor/settings'
      fullPath: '/vendor/settings'
      preLoaderRoute: typeof VendorVendorSettingsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/_vendor/vendor/profile': {
      id: '/_vendor/vendor/profile'
      path: '/vendor/profile'
      fullPath: '/vendor/profile'
      preLoaderRoute: typeof VendorVendorProfileRouteImport
      parentRoute: typeof VendorRoute
    }
    '/_vendor/vendor/orders': {
      id: '/_vendor/vendor/orders'
      path: '/vendor/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof VendorVendorOrdersRouteImport
      parentRoute: typeof VendorRoute
    }
    '/_vendor/vendor/menu': {
      id: '/_vendor/vendor/menu'
      path: '/vendor/menu'
      fullPath: '/vendor/menu'
      preLoaderRoute: typeof VendorVendorMenuRouteImport
      parentRoute: typeof VendorRoute
    }
    '/_vendor/vendor/dashboard': {
      id: '/_vendor/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorVendorDashboardRouteImport
      parentRoute: typeof VendorRoute
    }
    '/_authenticated/admin/delivery-settings': {
      id: '/_authenticated/admin/delivery-settings'
      path: '/admin/delivery-settings'
      fullPath: '/admin/delivery-settings'
      preLoaderRoute: typeof AuthenticatedAdminDeliverySettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/vendor-applications/': {
      id: '/_authenticated/admin/vendor-applications/'
      path: '/admin/vendor-applications'
      fullPath: '/admin/vendor-applications'
      preLoaderRoute: typeof AuthenticatedAdminVendorApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/terango-store/': {
      id: '/_authenticated/admin/terango-store/'
      path: '/admin/terango-store'
      fullPath: '/admin/terango-store'
      preLoaderRoute: typeof AuthenticatedAdminTerangoStoreIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/terango-products/': {
      id: '/_authenticated/admin/terango-products/'
      path: '/admin/terango-products'
      fullPath: '/admin/terango-products'
      preLoaderRoute: typeof AuthenticatedAdminTerangoProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/subscriptions/': {
      id: '/_authenticated/admin/subscriptions/'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/featured/': {
      id: '/_authenticated/admin/featured/'
      path: '/admin/featured'
      fullPath: '/admin/featured'
      preLoaderRoute: typeof AuthenticatedAdminFeaturedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/broadcasts/': {
      id: '/_authenticated/admin/broadcasts/'
      path: '/admin/broadcasts'
      fullPath: '/admin/broadcasts'
      preLoaderRoute: typeof AuthenticatedAdminBroadcastsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/analytics/': {
      id: '/_authenticated/admin/analytics/'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/advertisements/': {
      id: '/_authenticated/admin/advertisements/'
      path: '/admin/advertisements'
      fullPath: '/admin/advertisements'
      preLoaderRoute: typeof AuthenticatedAdminAdvertisementsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/terango-store/settings': {
      id: '/_authenticated/admin/terango-store/settings'
      path: '/admin/terango-store/settings'
      fullPath: '/admin/terango-store/settings'
      preLoaderRoute: typeof AuthenticatedAdminTerangoStoreSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/terango-store/orders': {
      id: '/_authenticated/admin/terango-store/orders'
      path: '/admin/terango-store/orders'
      fullPath: '/admin/terango-store/orders'
      preLoaderRoute: typeof AuthenticatedAdminTerangoStoreOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminDeliverySettingsRoute: typeof AuthenticatedAdminDeliverySettingsRoute
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
  AuthenticatedCategoriesIndexRoute: typeof AuthenticatedCategoriesIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedDriversIndexRoute: typeof AuthenticatedDriversIndexRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedSubcategoriesIndexRoute: typeof AuthenticatedSubcategoriesIndexRoute
  AuthenticatedVendorsIndexRoute: typeof AuthenticatedVendorsIndexRoute
  AuthenticatedAdminTerangoStoreOrdersRoute: typeof AuthenticatedAdminTerangoStoreOrdersRoute
  AuthenticatedAdminTerangoStoreSettingsRoute: typeof AuthenticatedAdminTerangoStoreSettingsRoute
  AuthenticatedAdminAdvertisementsIndexRoute: typeof AuthenticatedAdminAdvertisementsIndexRoute
  AuthenticatedAdminAnalyticsIndexRoute: typeof AuthenticatedAdminAnalyticsIndexRoute
  AuthenticatedAdminBroadcastsIndexRoute: typeof AuthenticatedAdminBroadcastsIndexRoute
  AuthenticatedAdminFeaturedIndexRoute: typeof AuthenticatedAdminFeaturedIndexRoute
  AuthenticatedAdminSubscriptionsIndexRoute: typeof AuthenticatedAdminSubscriptionsIndexRoute
  AuthenticatedAdminTerangoProductsIndexRoute: typeof AuthenticatedAdminTerangoProductsIndexRoute
  AuthenticatedAdminTerangoStoreIndexRoute: typeof AuthenticatedAdminTerangoStoreIndexRoute
  AuthenticatedAdminVendorApplicationsIndexRoute: typeof AuthenticatedAdminVendorApplicationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminDeliverySettingsRoute:
    AuthenticatedAdminDeliverySettingsRoute,
  AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
  AuthenticatedCategoriesIndexRoute: AuthenticatedCategoriesIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedDriversIndexRoute: AuthenticatedDriversIndexRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedSubcategoriesIndexRoute: AuthenticatedSubcategoriesIndexRoute,
  AuthenticatedVendorsIndexRoute: AuthenticatedVendorsIndexRoute,
  AuthenticatedAdminTerangoStoreOrdersRoute:
    AuthenticatedAdminTerangoStoreOrdersRoute,
  AuthenticatedAdminTerangoStoreSettingsRoute:
    AuthenticatedAdminTerangoStoreSettingsRoute,
  AuthenticatedAdminAdvertisementsIndexRoute:
    AuthenticatedAdminAdvertisementsIndexRoute,
  AuthenticatedAdminAnalyticsIndexRoute: AuthenticatedAdminAnalyticsIndexRoute,
  AuthenticatedAdminBroadcastsIndexRoute:
    AuthenticatedAdminBroadcastsIndexRoute,
  AuthenticatedAdminFeaturedIndexRoute: AuthenticatedAdminFeaturedIndexRoute,
  AuthenticatedAdminSubscriptionsIndexRoute:
    AuthenticatedAdminSubscriptionsIndexRoute,
  AuthenticatedAdminTerangoProductsIndexRoute:
    AuthenticatedAdminTerangoProductsIndexRoute,
  AuthenticatedAdminTerangoStoreIndexRoute:
    AuthenticatedAdminTerangoStoreIndexRoute,
  AuthenticatedAdminVendorApplicationsIndexRoute:
    AuthenticatedAdminVendorApplicationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface VendorRouteChildren {
  VendorVendorDashboardRoute: typeof VendorVendorDashboardRoute
  VendorVendorMenuRoute: typeof VendorVendorMenuRoute
  VendorVendorOrdersRoute: typeof VendorVendorOrdersRoute
  VendorVendorProfileRoute: typeof VendorVendorProfileRoute
  VendorVendorSettingsRoute: typeof VendorVendorSettingsRoute
  VendorSubscriptionIndexRoute: typeof VendorSubscriptionIndexRoute
  VendorVendorIndexRoute: typeof VendorVendorIndexRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorVendorDashboardRoute: VendorVendorDashboardRoute,
  VendorVendorMenuRoute: VendorVendorMenuRoute,
  VendorVendorOrdersRoute: VendorVendorOrdersRoute,
  VendorVendorProfileRoute: VendorVendorProfileRoute,
  VendorVendorSettingsRoute: VendorVendorSettingsRoute,
  VendorSubscriptionIndexRoute: VendorSubscriptionIndexRoute,
  VendorVendorIndexRoute: VendorVendorIndexRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  VendorRoute: VendorRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  authUnauthorizedRoute: authUnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
